
version: "3"
services:
  vue-client:
    build: 
      context: ./vue-client
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ".:/app"
  express-server:
    build: 
      context: ./express-server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/app"
    environment:
      WAIT_HOSTS: database:27017
    links:  
      - database
  database:
    image: mongo:4.0
    env_file:
      - ./.env
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
